[package]
name = "kestrel-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.92"
kestrel-crypto = "1.0.1"
getrandom = { version = "0.2.14", features = ["js"] }

[profile.release]
strip = "debuginfo"
lto = true
